### PR TITLE
Round of tweaks

### PR DESCRIPTION
**Pull request by titoBouzout**
A round of tweaks based on the experience using it

- add list of themes and languages to the readme
- add npm command for continuous watch and build
- add missing attributes to readme
- update types please double-check!
- had to avoid `overflow:auto` in the css because when the user tries to control scroll you will get a double scrollbar
- size to container, it gets rid of width and height settings
- removes z-index because it mess up with unrelated elements stacking (example a sticky positioned heading, the code gets behind the text but above the background of that heading)

### CODE REVIEW

**Comment by bigmistqke** [comment]
LGTM! thanks tito!

**Comment by titoBouzout** [comment]
Messed up the build-watch command but there its fixed :)

**Comment by bigmistqke** [comment]
The removal of `overflow: auto` does seem to break some styling, noticable in the dev-example:

https://github.com/user-attachments/assets/25c806f6-954b-4b7b-8cf4-ff3963d7454c

Could u share a code-snippet so i can see the initial double scrollbar issue? Maybe we should offer css-variables to style them, like we do with `--padding`.

PS: there was a bug in `dev` where it didn't show the textarea because the `solid-shiki-textarea/custom-element` import got removed accidentally: [i pushed a fix](https://github.com/bigmistqke/solid-shiki-textarea/commit/f8f613667f8521da4c038e1754e7adf9858b531d).

**Review by bigmistqke — COMMENTED** [review]
Some codestyle bikeshedding: I use sortcss-extension in vscode to sort the css-declarations concentrically. I would prefer to have them all as one block and sorted with sortcss or a similar extension that sorts the css declarations concentrically.

It's ugly, but consistent. And makes it 1 less thing to design/think about. I added it to the recommended vscode-settings in [this commit](https://github.com/bigmistqke/solid-shiki-textarea/commit/82a485cd81804cce3cbd8038811af7fa532db7f7)

**Comment by bigmistqke** [comment]
maybe we should make a couple of layouts with `<shiki-textarea/>` and `<ShikiTextarea/>` for testing purposes 🤔

**Comment by bigmistqke** [comment]
thanks tito!

**Comment by titoBouzout** [comment]
letsssss goo! Thank you too!

**Pull request merged**
